#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing!'
# Check Prettier
npm run check-format ||
{
    echo 'Pretty Check Failed. Run "npm run format", add changes and try to commit again!';
}
# Check ESLint
npm run check-lint ||
{
    echo 'ESLint Check Failed. Make the required changes listed above, add changes, and try to commit again!';
    false;
}
# Check TS Config
npm run check-types ||
{
    echo 'Type Check Failed. Make the necessary changes above, add changes, and try to commit again!';
    false;
}
# Check Build
npm run build ||
{
    echo 'Build process failed. Check the error above';
    false;
}

echo 'Success committed and ready to push!'